"""Init table

Revision ID: 1f0e865eb5e0
Revises: 
Create Date: 2024-01-30 17:07:00.917909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f0e865eb5e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), sa.Identity(always=False)),
    sa.Column('trip_id', sa.String()),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('pickup_datetime', sa.DateTime(), nullable=True),
    sa.Column('dropoff_datetime', sa.DateTime(), nullable=True),
    sa.Column('passenger_count', sa.Integer(), nullable=True),
    sa.Column('pickup_longitude', sa.Float(), nullable=True),
    sa.Column('pickup_latitude', sa.Float(), nullable=True),
    sa.Column('dropoff_longitude', sa.Float(), nullable=True),
    sa.Column('dropoff_latitude', sa.Float(), nullable=True),
    sa.Column('store_and_fwd_flag', sa.String(), nullable=True),
    sa.Column('trip_duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips')
    # ### end Alembic commands ###
