# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # need checkout before using compose-action
      - uses: actions/checkout@v4

      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"
          down-flags: "--volumes"
          services: |
            postgres

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - run: python3 -m venv .venv && source .venv/bin/activate && python3 -m pip install pipenv && pipenv install && python3 -m pytest tests/
